version: '3.5'

services:
  backend:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis_db
    env_file:
      - ./.env
    ports:
      - "8000:80"

  redis_db:
    container_name: redis_db
    command: bash -c "redis-server --appendonly yes"
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data