aggregate:
  path: /aggregate
  controller: App\Controller\ApiController::aggregate
  methods: [ POST ]

meta-description:
  path: /meta-description
  controller: App\Controller\ApiController::metaDescription
  methods: [ GET ]